package src.ontologia;
import jadex.adapter.fipa.AgentAction;
import src.Jugador.Jugador;

public class Request_unirse_partida extends AgentAction{
	/*
	 * RequestJoin.java
	 *
	 * Generated by Protege plugin Beanynizer. 
	 * Changes will be lost! 
	 */
	/**
	 *  Java class for concept RequestJoin of blackjack_beans ontology.
	 */
	
		//-------- constants ----------

		//-------- attributes ----------

		/** Attribute for slot timeout. */
		protected  int  timeout;

		/** Attribute for slot player. */
		protected  Jugador  jugador;

		//-------- constructors --------

		/**
		 *  Default Constructor. <br>
		 *  Create a new <code>RequestJoin</code>.
		 */
		public Request_unirse_partida()  {
		}

		//-------- accessor methods --------

		/**
		 *  Get the timeout of this RequestJoin.
		 * @return timeout
		 */
		public int  getTimeout() {
			return this.timeout;
		}

		/**
		 *  Set the timeout of this RequestJoin.
		 * @param timeout the value to be set
		 */
		public void  setTimeout(int timeout) {
			this.timeout = timeout;
		}

		/**
		 *  Get the player of this RequestJoin.
		 * @return player
		 */
		public Jugador  getJugador() {
			return this.jugador;
		}

		/**
		 *  Set the player of this RequestJoin.
		 * @param player the value to be set
		 */
		public void  setJugador(Jugador player) {
			this.jugador = player;
		}

		//-------- bean related methods --------


	}



